---
title: "Index"
output:
  html_document: default
  pdf: default
---

```{r}
library(tidyverse)
library(factoextra)
library(scales)
library(readxl)
library(knitr)
```

## Data Reading
```{r} 
lang19 <- read.csv("ACSDT5Y2019.C16001-Data.csv") 
lang24 <- read.csv("ACSDT5Y2024.C16001-Data.csv")
age <- read.csv("ACSDT5Y2024.B16004-Data.csv")
pov <- read.csv("ACSDT5Y2024.B16009-Data.csv")
igp <- read.csv("Cleaned BEU.csv")
digwh <- read.csv("ACSDT5Y2024.B28009A.csv") 
digbl <- read.csv("ACSDT5Y2024.B28009B.csv")
digas <- read.csv("ACSDT5Y2024.B28009D.csv")
dighs <- read.csv("ACSDT5Y2024.B28009I.csv")
digot <- read.csv("ACSDT5Y2024.B28009F.csv")
vuledu <- read.csv("BEU/Educational_Services.csv")
vulfin <- read.csv("BEU/Finance_and_Insurance.csv")
vulgov <- read.csv("BEU/Government.csv")
vulhlt <- read.csv("BEU/Health_Care_and_Social_Assistance.csv")
vulinf <- read.csv("BEU/Information.csv")
vulothr <- read.csv("BEU/Other_Services_Except_Public_Administration_.csv")
vulpro <- read.csv("BEU/Professional_Scientific_and_Technical_Services.csv")
vulret <- read.csv("BEU/Real_Estate_and_Rental_and_Leasing.csv")
vultrp <- read.csv("BEU/Transportation_and_Warehousing.csv")
vulutl <- read.csv("BEU/Utilities.csv")
df <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR2Ouwi_7tjwsP87vmH477lwU1YmvVd7qcU53BE5ln1DNQZe9GRRLGAdQn5b90fqZ0Rw85EFXj1PCla/pub?gid=572838345&single=true&output=csv") 
colnames(df)[1]= "Category" 
nlang <- ncol(df)
df <- df %>%
  pivot_longer(
    cols = - Category, 
    names_to = "language", 
    values_to = "count")
namelang <- unique(df$language)
namecat <- unique(df$Category)
grouplang <- c("Spanish", "Asian", "Indo_Euro", "Other")
racelang <- c("White", "Black", "Asian", "Hispanic")
namelang[3] <- "Tagalog"
namelang[7] <- "Haitian"
langroup <- tibble(
  language = c("Spanish", "Chinese", "Tagalog", "Korean", "Vietnamese", "Japanese", "Portuguese", "German", "Haitian", "French", "Hindi", "Russian", "Arabic"),
  group = c("Spanish", "Asian", "Asian", "Asian", "Asian", "Asian", "Indo_Euro", "Indo_Euro", "Indo_Euro", "Indo_Euro", "Indo_Euro", "Indo_Euro", "Other")
)
finalize <- function(x){
  return(log(x+1))
  }
```

## Laplace smoothing for current availability
```{r}
alpha <- 0.01 # could be adjusted afterwards
K <- nlang + 1
total <- nrow(df)
df <- df %>%
  mutate(
    supply = (count + alpha)/(total + K*alpha),
    language = recode(language, 
      "Tagalog..incl..Filipino." = "Tagalog",
      "Haitian..Creole." = "Haitian"
    )
  ) %>%
  left_join(langroup, by = "language")

```

## Proportion of Limited English Proficiency (LEP)
```{r}
lang24 <- lang24 %>%
  slice(-1) %>%
  select(-contains("M"),
         -contains("X")) %>%
  mutate(across(-c(1, 2), as.numeric))
lep <- c(
  lang24[[6]]/lang24[[4]], # Spanish
  lang24[[24]]/lang24[[22]], # Chinese
  lang24[[30]]/lang24[[28]], # Tagalog
  lang24[[18]]/lang24[[16]], # Portuguese (Calculated as "Other Indo-European languages")
  lang24[[21]]/lang24[[19]], # Korean
  lang24[[12]]/lang24[[10]], # German
  lang24[[9]]/lang24[[7]], # Haitian
  lang24[[27]]/lang24[[25]], # Vietnamese
  lang24[[9]]/lang24[[7]], # French
  lang24[[18]]/lang24[[16]], # Hindi (Calculated as "Other Indo-European languages")
  lang24[[36]]/lang24[[34]], # Arabic
  lang24[[33]]/lang24[[31]], # Japanese (Calculated as "Other Asian languages")
  lang24[[15]]/lang24[[13]] # Russian
)
lepgroup <- tibble(
  language = namelang,
  lep = lep
)
df <- df %>%
  left_join(lepgroup, by = "language")
```

## Population Growth Rate (PGR)
```{r}
lang19 <- lang19 %>%
  slice(-1) %>%
  select(-contains("M"),
         -contains("X")) %>%
  mutate(across(-c(1, 2), as.numeric))
pgr <- c()
for (i in c(4, 22, 28, 16, 19, 10, 7, 25, 7, 16, 34, 31, 13))
  pgr <- c(pgr, lang24[[i]]/lang19[[i]]-1)
grpgroup <- tibble(
  language = namelang,
  pgr = pgr
)
df <- df %>%
  left_join(grpgroup, by = "language")
```

## Age (TEEN/ELDER)
```{r}
age <- age %>%
  slice(-1) %>%
  select(-contains("M"),
         -contains("X")) %>%
  mutate(across(-c(1, 2), as.numeric))
total <- c(
  age[[5]]+age[[27]]+age[[49]], #Spanish
  age[[15]]+age[[37]]+age[[59]], #Asian
  age[[10]]+age[[32]]+age[[54]], #Indo-Euro
  age[[20]]+age[[42]]+age[[64]] #Other
)
teen <- c(age[[5]], age[[15]], age[[10]], age[[20]])/total
elder <- c(age[[49]], age[[59]], age[[54]], age[[64]])/total
agegroup <- tibble(
  group = grouplang,
  teen = teen,
  elder = elder
)
df <- df %>%
  left_join(agegroup, by = "group")
```

## Poverty (POV)
```{r}
pov <- pov %>%
  slice(-1) %>%
  select(-contains("M"),
         -contains("X")) %>%
  mutate(across(-c(1, 2), as.numeric))
```
```{r}
total <- c(
  pov[[6]]+pov[[12]]+pov[[19]]+pov[[25]], #Spanish
  pov[[8]]+pov[[14]]+pov[[21]]+pov[[27]], #Asian
  pov[[7]]+pov[[13]]+pov[[20]]+pov[[26]], #Indo_Euro
  pov[[9]]+pov[[15]]+pov[[22]]+pov[[28]] #Other
)
pov <- c(pov[[6]]+pov[[12]], pov[[8]]+pov[[14]], pov[[7]]+pov[[13]], pov[[9]]+pov[[15]])/total
povgroup <- tibble(
  group = grouplang,
  pov = pov
)
df <- df %>%
  left_join(povgroup, by = "group")
```
```{r}
df
```

## Industry Gross Product Proportion (IGP)
```{r}
igpdata <- read.csv("Cleaned BEU.csv")
igpgroup <- igpdata %>%
  mutate(
    igp = prop
  ) %>%
  select(Category, igp)
df <- df %>%
  left_join(igpgroup, by = "Category")
```

## Vulnerability (VUL)
```{r}
dfbeu <- read_excel("Work Context.xlsx")
Edup <- vuledu %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Edu <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vuledu$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Edup, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Finp <- vulfin %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Fin <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulfin$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Finp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Govp <- vulgov %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Gov <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulgov$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Govp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Hltp <- vulhlt %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Hlt <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulhlt$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Hltp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Infp <- vulinf %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Info <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulinf$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Infp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Othrp <- vulothr %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Othr <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulothr$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Othrp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Prop <- vulpro %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Pro <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulpro$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Prop, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Retp <- vulret %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Ret <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulret$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Retp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Trpp <- vultrp %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Trp <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vultrp$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Trpp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

Utlp <- vulutl %>%
  select(Employed.by.this.Industry, Code) %>%
  rename(`O*NET-SOC Code` = Code)
Utl <- dfbeu %>%
  filter(`O*NET-SOC Code` %in% vulutl$Code ) %>%
  select(`O*NET-SOC Code`, `Data Value`) %>%
  left_join(Utlp, by = "O*NET-SOC Code") %>%
  mutate(
    emply = parse_number(Employed.by.this.Industry)/100,
    Score = emply*`Data Value`
  )

vul <- tibble(
  vul = c(mean(Edu$Score),
          mean(Fin$Score),
          mean(Gov$Score),
          mean(Hlt$Score),
          mean(Info$Score),
          mean(Othr$Score),
          mean(Pro$Score),
          mean(Ret$Score),
          mean(Trp$Score),
          mean(Utl$Score)
  ),
  Category = namecat
)

df <- df %>%
  left_join(vul, by = "Category")
```

## Legal Compliance (LGL)
```{r}
lgl = c(1, 0.5, 1, 1, 0, 0, 0, 0, 1, 1) # According to Title VI of the Civil Rights Act and Executive Order 13166, while parts of finace is asked to provide translation services
lglgroup <- tibble(
  lgl = lgl,
  Category = namecat
  )
df <- df %>%
  left_join(lglgroup, by = "Category")
```


## Digital Access (DIG)
```{r}
dig <- digwh %>%
  mutate(
    white = parse_number(Gainesville.CCD..Alachua.County..Florida..Estimate),
    black = parse_number(digbl$Gainesville.CCD..Alachua.County..Florida..Estimate),
    asian = parse_number(digas$Gainesville.CCD..Alachua.County..Florida..Estimate),
    hispanic = parse_number(dighs$Gainesville.CCD..Alachua.County..Florida..Estimate),
    other = parse_number(digot$Gainesville.CCD..Alachua.County..Florida..Estimate)
  ) %>%
  select(white, black, asian, hispanic, other)
dap <- dig[2,]/dig[1,]
dig <- c(dap[[4]], dap[[3]],dap[[3]],dap[[3]],dap[[3]],dap[[3]],0.9*dap[[4]]+0.1*dap[[1]],dap[[1]],dap[[2]],0.6*dap[[1]]+0.4*dap[[2]],dap[[3]],dap[[1]],dap[[1]]) # No direct resources available for races proportion by language spoken
digroup <- tibble(
  dig = dig,
  language = namelang
)

df <- df %>%
  left_join(digroup, by = "language")
```

## Population perspective PCA
```{r}
pcaa <- df %>%
  select(lep, pgr, teen, elder, pov, dig) %>%
  drop_na()
pcaa <- prcomp(pcaa, scale. = TRUE)
fviz_eig(pcaa, addlables=TRUE, ylim = c(0, 100))
fviz_pca_var(pcaa, col.var = "contrib")
lang <- pcaa$rotation
v1 <- pcaa$sdev^2
p1 <- v1 / sum(v1)
cl <- v1[1]*lang[, 1] +v1[2]*lang[, 2]
df <- df %>%
  mutate(
    lang =  finalize(cl[1]*lep + cl[2]*pgr + cl[3] *teen + cl[4] *elder + cl[5]*pov +cl[6]*dig)
  )
```
## Industry Perspective PCA
```{r}
pcab <- df %>%
  select(vul, lgl, igp) %>%
  drop_na()
pcab <- prcomp(pcab, scale. = TRUE)
fviz_eig(pcab, addlables=TRUE, ylim = c(0, 100))
fviz_pca_var(pcab, col.var = "contrib")

# Remove igp
pcabn <- df %>%
  select(vul, lgl) %>%
  drop_na()
pcabn <- prcomp(pcabn, scale. = TRUE)
fviz_eig(pcabn, addlables=TRUE, ylim = c(0, 100))
fviz_pca_var(pcabn, col.var = "contrib")
indy <- pcabn$rotation
v2 <- pcabn$sdev^2
p2 <- v2 / sum(v2)
ci <- v2[1]*indy[, 1]
ci
df <- df %>%
  mutate(
    indy =  finalize(abs(ci[1]*vul + ci[2] *lgl))
  )
```
```{r}
df <- df %>%
  mutate(
    index = supply/lang/indy,
    index = finalize(index/mean(index))
  ) %>%
  select(Category, language, index)
```

## Arrangment & Final Result
```{r}
top <- df %>%
  arrange(desc(index))
top
```
```{r}
last <- df %>%
  arrange(index)
last
```
```{r}
kable(top[, c("language", "Category", "index")], 
      caption = "Language Access Availability in Gainesville")
write.csv(top, "Language Access Availability in Gainesville.csv", row.names = FALSE)
```












