get---
title: "B05006"
output: html_document
---

```{r}
library(dplyr)
library(purrr)
library(tidyverse)
```

```{r}
raw <- list.files(path = "../Raw Data CCD", pattern = "B05006-Data.csv", full.names = TRUE,  recursive = TRUE)
all_dfs <- list() 
for (i in raw) {
  Year <- as.numeric(str_extract(i, "20\\d{2}"))
  temp <- read.csv(i, skip = 1, stringsAsFactors = FALSE)
  names(temp) <- names(temp) %>%
    str_replace_all("[:!\\.]", "_") %>% 
    str_replace_all("_+", "_") %>%
    str_remove("_$") %>%
    str_trim()
  temp$Year <- Year
  all_dfs[[i]] <- temp
}
all_data <- bind_rows(all_dfs) %>%
  select(Year, everything()) %>%
  select(-contains("Margin")) %>%
  select(-"X")
```

```{r}
long_region_end <- "(?<!Other_)South_Central_Asia$|(?<!Other_)South_Eastern_Asia$|(?<!Other_)Australia_and_New_Zealand_Subregion$"
all_cols <- colnames(all_data)
keep_cols <- all_cols[str_count(all_cols, "_") <= 4|str_detect(all_cols, "n_e_c")|str_detect(all_cols, long_region_end)]
```

```{r}
final_data <- all_data %>%
  select(all_of(keep_cols))
write.csv(final_data, "B05006.csv", row.names = TRUE)
```